### ISSUE TITLE
demo_wavelets bug: Wk.synthesis(S) 

### ISSUE THREAD

**Issue by donnate** [epfl-lts2/pygsp#1]
Hello!

I have just downloaded the package using pip install, and I have been trying to reproduce the code as shown on the Graphlet tutorial, but I keep encountering the same error when trying to place a Kronecker signal at a specific vertex by running:
Sf = Wk.synthesis(S)

Error:
cheb_coeffs = operator.compute_cheby_coeff(self, m=order, N=order + 1)
AttributeError: 'module' object has no attribute 'compute_cheby_coeff'. 

It seems that the code calls the function filter.py, which, at line 221, calls:
cheb_coeffs = operator.compute_cheby_coeff(self, m=order, N=order + 1)
whereas it should probably call:
cheb_coeffs =  fast_filtering.compute_cheby_coeff(self, m=order, N=order + 1)
(seems to work after correcting like this at least...)
I was thus wondering if the toolbox had been updated and if something had perhaps changed?
Thanks for your time and help.

C.D.

Details: anaconda/python2.7; Mac OS Sierra 10.12.3

**Comment by lionel-martin** [comment]
Hello,

The devel branch has been updated to fix this typo following code rearrangement.
Thank you for the notice!
