### ISSUE TITLE
need to add nngraphs to requirements list

### ISSUE THREAD

**Issue by Gibbsdavidl** [epfl-lts2/pygsp#10]
Hello,

In update_graph_attr(self, *args, **kwargs) you import "from nngraphs import NNGraph" but do not list this in the requirements.txt and the function fails without it.

I believe this comes from torch?

Thanks!
-dave

**Comment by mdeff** [comment]
Hello, `nngraphs` is the [sub-package of `pygsp/graphs`](https://github.com/epfl-lts2/pygsp/tree/master/pygsp/graphs/nngraphs) where the `NNGraph` class is defined. Are you actually encountering an error?

**Comment by mdeff** [comment]
There was indeed an issue. ce861c67008efffe3f5dee784d8854d43d5c57e1 fixed it. Thanks for reporting!
