### ISSUE TITLE
Inability of handling large matrix due to dense matrix operation in Graph.compute_fourier_basis

### ISSUE THREAD

**Issue by cby120** [epfl-lts2/pygsp#107]
PyGSP supports sparse adjacent matrix input, however when computing fourier basis, it uses numpy.linalg.eigh and converted W to dense, which limits the capacity of matrix scale, especially sparse connections. 
```Python
fourier.py - L103
    self._e, self._U = np.linalg.eigh(self.L.toarray())
```
Is it possible to replace it with scipy.sparse.linalg.eigsh, in order to support sparse operation and improve the ability to deal with large graphs ?

Thanks developers !

**Comment by nperraud** [comment]
Hi @cby120 
Since we compute all eigenvalues and eigenvectors, I believe there is no gain possible with `eigsh`.

**Comment by cby120** [comment]
Hello, @nperraud 
I've done some research. It seems like `scipy.linalg.eigsh` will return the decomposed matrix in dense format. So the results would unable to allocate memory the same as `numpy.linalg.eigsh`. Thank you for responding. 
But if scipy updates new decomposition function that returns sparse-formatted results, this may help to deal with larger sparse matrices, as a potential improvement I hope. 
Best wishes !
