### ISSUE TITLE
Tutorial doesn't work

### ISSUE THREAD

**Issue by mada-ko** [epfl-lts2/pygsp#14]
I downloaded the package using pip and I tried "Introduction to the PyGSP" in tutorials.
And I encountered the below error when running the code.

Code:
import numpy as np
from pygsp import graphs, filters, plotting
plotting.BACKEND = 'matplotlib'
G = graphs.Logo()
G.compute_fourier_basis()
print(G.U)
G.plot_signal(G.U[:, 1], vertex_size=50)

Error:
TypeError: pg_plot_signal() got an unexpected keyword argument 'show_plot'

I use:
MacOS Sierra 10.12.6
python 3.6
PyGSP (0.4.1)

**Comment by mdeff** [comment]
That's because you are following the tutorial of the **master version** while you've installed **version 0.4** with pip.

Please either install the master version with
```
git clone git@github.com:epfl-lts2/pygsp.git
pip install -e pygsp
```

Or follow the [tutorial for 0.4](http://pygsp.readthedocs.io/en/v0.4/tutorials/demo.html).

**Comment by mada-ko** [comment]
Thank you for your reply.
I have installed the master version and the tutorials worked.
But the graph was not shown by running G.plot() and G.plot_signal(G.U[:, 1], vertex_size=50).
When I run the tutorials code, any error was not raised.

**Comment by mdeff** [comment]
That was because you needed to call `plt.show()` or use `%matplotlib inline` in Jupyter notebooks for plots to show up using the matplotlib backend. I've changed that behavior and now plots will show up automatically. Thanks for reporting this!

**Comment by mada-ko** [comment]
I have resolved the problem by using %matplotlib inline.
Thanks for your support.
