### ISSUE TITLE
compute_fourier_basis Assertion Error

### ISSUE THREAD

**Issue by lucy3** [epfl-lts2/pygsp#20]
I'm having trouble getting past `assert self._e[-1] <= 2` with a graph when I try to compute its fourier basis, so I'm wondering in why this assertion would fail? Why does the largest eigenvalue have to be <= 2?

**Comment by lucy3** [comment]
Hmmm... this is strange, then. The minimum weight in my weight matrix is 1 and G.is_directed() returns False. Any other possible reasons this would fail?

**Comment by nperraud** [comment]
It really looks like a numerical error. We should relax slightly the assertion. I will do it this afternoon.
Thanks for reporting this bug.

**Comment by nperraud** [comment]
Could you print for us `self._e[-1]-2`?

**Comment by lucy3** [comment]
It prints out 4.84057238737e-14.

**Comment by mdeff** [comment]
It's indeed a numerical issue then (your largest eigenvalue is marginally above 2). We'll relax the assertion. In the mean time you can just comment it. Thanks for reporting!

**Comment by mdeff** [comment]
That was fixed in 58421d553e8929e145a14b194ed0d335c6942296.
