### ISSUE TITLE
plotting.plot_spectogram not working on Jupyter-Notebook

### ISSUE THREAD

**Issue by divyanshusrivastava** [epfl-lts2/pygsp#25]
This is also the case when the backend is chosen as 'pyqtgraph' for any plotting function call. The screen gets stuck on an empty window, and the kernel dies on closing it.

**Comment by mdeff** [comment]
As you discovered, `plotting.plot_spectogram` is only available with the `pyqtgraph` backend. It should be possible to use it from the notebook by invoking the [`%gui qt5` magic](http://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-gui).

**Comment by divyanshusrivastava** [comment]
Indeed. 
It's working now. 

Thanks.
