### ISSUE TITLE
kernel_lowpass has arguments when being called in Expwin source code, what value for x is being passed?

### ISSUE THREAD

**Issue by shreyashi2104** [epfl-lts2/pygsp#49]
Taken from expwin.py in pygsp:

`def kernel_lowpass(x):
            return h(0.5 - x/G.lmax + band_max)
        def kernel_highpass(x):
            return h(0.5 + x/G.lmax - band_min)

        if (band_min is None) and (band_max is None):
            kernel = lambda x: np.ones_like(x)
        elif band_min is None:
            kernel = kernel_lowpass  #Here what value of x is being passed
        elif band_max is None:
            kernel = kernel_highpass  #Here what value of x is being passed
        else:
            kernel = lambda x: kernel_lowpass(x) * kernel_highpass(x)`

This doubt came to my mind when I wanted to use expwin as high pass filter for my graph. Is this a glitch?

**Comment by nperraud** [comment]
I am not sure I understand your concern. I just tested `expwin` and everything seems alright.

```
import numpy as np
from pygsp.filters import Expwin
from pygsp.graphs import Sensor
from matplotlib import pyplot as plt

N = 100
slope = 4
G = Sensor(N)
G.estimate_lmax()
f1 = filters.expwin.Expwin(G, band_min=None, band_max=0.4, slope=slope)
f2 = filters.expwin.Expwin(G, band_min=0.2, band_max=None, slope=slope)
f3 = filters.expwin.Expwin(G, band_min=0.2, band_max=0.4, slope=slope)
plt.figure(figsize=(15,4))
ax = plt.subplot(131)
f1.plot(ax=ax);
ax = plt.subplot(132)
f2.plot(ax=ax);
ax = plt.subplot(133)
f3.plot(ax=ax);
```

**Comment by shreyashi2104** [comment]
I wanted to know from the source code how kernel_lowpass is being called
without arguments in case of band max or band min being None

**Comment by nperraud** [comment]
The function kernel_low pass is defined above taking the argument into account. I am closing the issue since this is not pygsp related.
