### ISSUE TITLE
doc/tutorials/demo.rst typo

### ISSUE THREAD

**Issue by diego-sacconi** [epfl-lts2/pygsp#5]
[demo.rst](https://github.com/epfl-lts2/pygsp/blob/master/doc/tutorials/demo.rst) says:

> You can now access the eigenvalues of the fourier basis with G.e and the eigenvectors G.U, they look like sinuses on the graph. Let's plot the second and third eigenvector, as the one is only constant.

But then, since the index starts at 0, it plots the third and the fourth ones:

```
pygsp.plotting.plt_plot_signal(G, G.U[:, 2], savefig=True, vertex_size=50, plot_name='doc/tutorials/img/logo_second_eigenvector')
pygsp.plotting.plt_plot_signal(G, G.U[:, 3], savefig=True, vertex_size=50, plot_name='doc/tutorials/img/logo_third_eigenvector')
```

**Comment by mdeff** [comment]
Indeed. Thanks for pointing it out. Fixed by 2729440e559b62dd91a06d2b3e43c4c2b84530de.

**Comment by diego-sacconi** [comment]
Also, at the end of the file there is a not working reference:
```
 So here are the basics for the PyGSP toolbox, if you want more informations you can check the doc in :ref:`the reference guide section <reference-guide>`.
```
Have a nice day :+1:

**Comment by mdeff** [comment]
It does at least work on the [website](https://lts2.epfl.ch/pygsp/tutorials/demo.html). Am I missing something?

**Comment by diego-sacconi** [comment]
Probably it was my mistake since it seems to work fine. Sorry for disturbing!

**Comment by mdeff** [comment]
No problem. Thanks for your help :)
