### ISSUE TITLE
Trouble in from_networkx and to_networkx

### ISSUE THREAD

**Issue by HowIII** [epfl-lts2/pygsp#58]
I am kind of new to Python. I installed the pygsp package in conda. But when I tried to use the to_networkx() function, it always said that the 'Graph' object has no attribute 'to_networkx'. Could someone help me ? Thanks!

**Comment by mdeff** [comment]
This function is only available in the development version of the PyGSP. It's not yet on PyPI nor conda-forge. If you want to use it, install the development version with `pip install git+https://github.com/epfl-lts2/pygsp` (rather than `pip install pygsp` or `conda install -c conda-forge pygsp`).

**Comment by HowIII** [comment]
Got it. Thanks for the answer!

**Comment by HowIII** [comment]
> Those functions are only available in the development version of the PyGSP. It's not yet on PyPI nor conda-forge. If you want to use it, install the development version with `pip install git+https://github.com/epfl-lts2/pygsp` (rather than `pip install pygsp` or `conda install -c conda-forge pygsp`).
Got it. Thanks for the answer!
