### ISSUE TITLE
Bugs in filter.py

### ISSUE THREAD

**Issue by diego-sacconi** [epfl-lts2/pygsp#6]
In **evaluate()** 'fd' is [assigned two times](https://github.com/epfl-lts2/pygsp/blob/70c27ee5970aa39d70f3717e989e08ac29d59369/pygsp/filters/filter.py#L157), the first seems useless:
```
fd = np.zeros(x.size)
fd = self.g[i](x)
return fd
```

********************

In **filterbank_bounds()** if 'bounds' is not provided it does:
```
if not hasattr(self.G, 'lmax'):
    self.logger.info('FILTERBANK_BOUNDS: Has to estimate lmax.')
    self.G.estimate_lmax()  

if not hasattr(self.G, 'e'):
    self.logger.info(
    'FILTERBANK_BOUNDS: Has to compute Fourier basis.')
    self.G.compute_fourier_basis()
     
rng = self.G.e
```
but **compute_fourier_basis()** in graph.py already [sets 'lmax'](https://github.com/epfl-lts2/pygsp/blob/0922f58eca5795ab57794a43d69a21eef46f4c1d/pygsp/graphs/graph.py#L536) when returning, so I think the first if block should be removed.

******************************

Hope it helps. Nice toolbox :+1:

**Comment by mdeff** [comment]
Thanks for pointing those out. First is evident. Second is reminiscent of the [matlab version](https://github.com/epfl-lts2/gspbox/blob/master/filters/gsp_filterbank_bounds.m) which may use `lmax` as `xmax`.
