### ISSUE TITLE
classification_tikhonov modifies one of its parameter taken in input

### ISSUE THREAD

**Issue by Algue-Rythme** [epfl-lts2/pygsp#71]
Hi,

The `learning.classification_tikhonov` function (and its variants) take the labels `y` as input. The user of the function should not expect this array to be modified. But because of `y[M == False] = 0` the array is modified, which is very annoying. Indeed, for validation purposes, it might be useful to store the real labels in `y[M == False]`. 

I suggest to either:

- document this behavior with a warning
- modify the function such that it starts by copying the data (that shouldn't be too expansive).

**Comment by nperraud** [comment]
Hi Algue-Rythme
Thank you very much for reporting this. This is plainly a bug that should be addressed. 
I believe that we should copy the data for this not happen.
I will make a PR very soon.

**Comment by nperraud** [comment]
Continuous integration is broken. We need to fix that before we can merge to master... But it is on the way.

**Comment by mdeff** [comment]
Sorry for the delay, I had to fix the CI before merging. Thanks @Algue-Rythme for reporting and @nperraud for fixing!
