### ISSUE TITLE
Bug in filter.py

### ISSUE THREAD

**Issue by diego-sacconi** [epfl-lts2/pygsp#8]
In **'synthesis()'** there's a call to ['operator.cheby_op'](https://github.com/epfl-lts2/pygsp/blob/master/pygsp/filters/filter.py#L236):
```
s = s + operator.cheby_op(self.G,
cheb_coeffs[i], c[i * N + tmpN])
```
but the function it's been moved to [fast_filtering.py](https://github.com/epfl-lts2/pygsp/blob/master/pygsp/operators/fast_filtering.py#L61)

**Comment by mdeff** [comment]
That's right. Thanks for catching it! :)
