### ISSUE TITLE
Install latest version with latest functionality

### ISSUE THREAD

**Issue by StefanBloemheuvel** [epfl-lts2/pygsp#88]
Dear creators of Pygsp,

I would like to install the latest version with all the latest functionality, labeled as 'latest' on the pygsp website. However, I cannot seem to find a way to do so. I found your suggestion on issue 82 where ```pip install https://github.com/epfl-lts2/pygsp``` should do the trick, however this returns a lot of errors to me:

```
pip install https://github.com/epfl-lts2/pygsp
Collecting https://github.com/epfl-lts2/pygsp
  Downloading https://github.com/epfl-lts2/pygsp
     - 174kB 1.9MB/s
  ERROR: Cannot unpack file /private/var/folders/bw/qvtg52mj1pz37rcd5nr8k8qc0000gn/T/pip-unpack-ee5p_yel/pygsp (downloaded from /private/var/folders/bw/qvtg52mj1pz37rcd5nr8k8qc0000gn/T/pip-req-build-s0ije3vi, content-type: text/html; charset=utf-8); cannot detect archive format
ERROR: Cannot determine archive format of /private/var/folders/bw/qvtg52mj1pz37rcd5nr8k8qc0000gn/T/pip-req-build-s0ije3vi
```

Do you know how to solve such an error or is there an easier way to install the version with the latest functionality?

**Comment by mdeff** [comment]
The proper command is `pip install git+https://github.com/epfl-lts2/pygsp` (I missed the `git+` part in #88, will edit).

**Comment by StefanBloemheuvel** [comment]
The code worked now, however, I still get errors when I try to run the code from https://pygsp.readthedocs.io/en/latest/reference/filters.html#pygsp.filters.Heat, since graph.n_vertices and the keyword 'scale' in filters.Heat(graph, scale=diffusivity*steps) are still unexpected. The version of pygsp that pip freeze tells me is PyGSP==0.5.1.

**Comment by mdeff** [comment]
You probably still have the stable not latest release. `pip` won't install the latest if the stable is already in your environment. Try to create a new environment, or install with `--ignore-installed` (i.e., `pip install --ignore-installed git+https://github.com/epfl-lts2/pygsp`).

**Comment by StefanBloemheuvel** [comment]
Thanks, that indeed did the trick!
